ProgDir: ./prog # 実行ファイルからの相対パスを指定
FileType: m4a
DownloadedHistoryConfFile: config/downloaded.yaml
Programs:
  - Name: カルチャーラジオ 科学と人間
    URL: https://www.nhk.or.jp/radioondemand/json/3065/bangumi_3065_01.json
